[tool.poetry]
name = "microstructure-price-prediction"
version = "0.1.0"
description = ""
authors = ["Mikhail Mironov, Maxim Shibanov"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
scrapy = "^2.11.2"
pandas = "^2.2.3"
polars = "^1.9.0"
numpy = "^2.1.1"
requests = "^2.32.3"
notebook = "^7.2.2"
ipykernel = "^6.29.5"
pytest = "^8.3.3"
scikit-learn = "^1.5.2"
linearmodels = "^6.1"
optuna = "^4.1.0"
ipywidgets = "^8.1.5"
plotly = "^5.24.1"
dash = "^2.18.2"
optuna-dashboard = "^0.17.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
